config/routes.rb
Rails.application.routes.draw do
  root 'charts#hello'

  resources :charts, only: :show do
    get 'not-found' => 'charts#not_found', as: 'not_found', on: :collection
    get 'data' => 'charts#data', on: :member
  end

  get '*unmatched_route', to: 'charts#not_found'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :users, through: :posts
  validates :date, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :entry
  has_many :users, dependent: :destroy

  def hunter
    users.hunter.first
  end

  def makers
    users.maker
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :post
  enum role: [ :hunter, :maker ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound do |exception|
    redirect_to not_found_charts_path
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  PH_ORANGE = "#da552f"

  def hello
    @entries = Entry.includes(:posts).order(date: :desc)
  end

  def show
    begin
      @entry = Entry.includes(:posts).find_by!(date: params[:id])
      @chart_data = @entry.posts.order(:rank).map do |post|
        { name: "##{post.rank} #{post.name}", data: post.series }
      end
      if params[:rank].present?
        rank = (1..5).include?(params[:rank].to_i) ?
          params[:rank].to_i : 1
      else
        rank = 1
      end
      @post = @entry.posts.find_by(rank: rank)
      @colors = ["#353535", "#6d6d6d", "#8d8d8d", "#aeaeae", "#dddddd"]
      @colors[rank - 1] = PH_ORANGE
    rescue ActiveRecord::StatementInvalid
      redirect_to not_found_charts_path
    end
  end

  def data
    begin
      @entry = Entry.find_by!(date: params[:id])
      render json: @entry
    rescue ActiveRecord::StatementInvalid
      redirect_to not_found_charts_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charts/hello.html.erb
<h1>Hello!</h1>

<p>This is the server part of
  <%= link_to '@tophuntsdaily', 'https://twitter.com/tophuntsdaily',
      target: '_blank'%>.
</p>

<p>If you like what you see, please
<%= link_to 'say hi', 'https://twitter.com/janklimo', target: '_blank'%>!
</p>

<p>Below you can find all the indexed dates. Have fun exploring!</p>

<table class="table-fill">
  <thead>
    <tr>
    <th class="text-left">Date</th>
    <th class="text-left">Top Products</th>
    <th class="text-left">Total Votes</th>
    <th class="text-left"></th>
    </tr>
  </thead>
  <tbody class="table-hover">
    <% @entries.each do |entry| %>
      <tr>
        <td class="text-left">
          <%= entry.date.strftime(" %b %-d, %Y") %>
        </td>
        <td class="text-left">
          <%= entry.posts.sort_by { |p| p['rank'] }.map { |p| p.name }.join(', ') %>
        </td>
        <td class="text-left">
          <%= entry.posts.inject(0) { |sum, p| sum + p.votes } %>
        </td>
        <td class="text-left">
          <%= link_to 'View', chart_path(entry.date) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/charts/not_found.html.erb
<h1>The requested chart does not exist :(</h1>

<p>Either the date is wrong or it has not been generated yet.</p>

app/views/charts/show.html.erb
<div class="container">
  <div class="header">
    <div class="logo-container">
      <%= image_tag 'ph-logo.png', alt: 'ph-logo', class: 'ph-logo' %>
    </div>
    <div class="headline-container">
      <h1 class='headline'>Most Upvoted Products of
        <%= @entry.date.strftime(" %b %-d, %Y") %>
      </h1>
      <h2 class="tagline">
        <span class="rank">#<%= @post.rank %></span>
        <%= @post.name %>
        <span class="count"> (<%= @post.votes %> votes)</span>
      </h2>
    </div>
    <div class="users-container">
      <div class="hunter-container">
        <div class="image-container">
          <%= image_tag @post.hunter.image_url, alt: 'thumbnail',
            id: 'hunter-thumb', class: 'thumb' %>
          <span class="badge hunter">H</span>
        </div>
      </div>
      <div class="makers-container">
        <% @post.makers.each_with_index do |maker, i| %>
          <div class="image-container">
            <%= image_tag maker.image_url, alt: 'thumbnail',
              id: "maker-#{i + 1}-thumb", class: 'thumb' %>
            <span class="badge maker">M</span>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <script type="text/javascript" charset="utf-8">
    Highcharts.setOptions({
      global: {
        timezoneOffset: 420
      }
    });
  </script>
  <div class="chart">
    <%= line_chart(@chart_data, colors: @colors,
    library: {
      plotOptions: {
        series: {
          animation: false
        }
      },
      chart: {
        height: 350
      }
    }) %>
  </div>
  <div class="footer">
    Charts by
    <span class="orange">@tophuntsdaily</span>
    <span class="separator">|</span>
    Data by
    <span class="orange">@producthunt</span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Top Hunts Daily</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>